# Usign the Clean Blog theme

title: A Numerical Tour of Data Science
email: gabriel.peyre@ceremade.dauphine.fr
description: > # this means to ignore newlines until "baseurl:"
  The Numerical Tours of Data Sciences, by Gabriel Peyré, gather Matlab, Python and Julia experiments to explore modern data science.
baseurl: ""
url: "www.numerical-tours.com"
github_username:  gpeyre

gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
