# Usign the Clean Blog theme

title: A Numerical Tour of Signal Processing
email: gabriel.peyre@ceremade.dauphine.fr
description: > # this means to ignore newlines until "baseurl:"
  The Numerical Tours of Signal Processing, by Gabriel Peyré, gather Matlab, Python and Scilab experiments to explore modern signal and image processing. 
baseurl: "/"
url: "www.numerical-tours.com"
github_username:  gpeyre

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]